### PR TITLE
Java 11 Support

### PR DESCRIPTION
**Pull request by er1c**

### CODE REVIEW

**Comment by er1c** [comment]
There are a bunch of various changes I was hacking on in here, some not related.  I need to isolate the specific fix(es), but one or many of these changes seems to fix the sporadic test-passing issue.

**Comment by er1c** [comment]
PR Updated, I isolated the single code change `.abort()` => `.close()` that fixes the issue.  I don't think there are any unintended side effects from the change, but worth reviewing again.

**Comment by tpunder** [comment]
Why are you adding a Jenkinsfile to this?  Does Travis not work for it?

**Comment by er1c** [comment]
Path of least resistance I guess, I forgot this was public.  We didn't have Travis setup, so would need to hook that up.

**Comment by tpunder** [comment]
Do you have tests that can explicitly trigger this bug?

**Comment by er1c** [comment]
> Do you have tests that can explicitly trigger this bug?

It triggers nearly 100% on OSX for me.  But I wasn't ever able to isolate exactly what was triggering this condition.

I removed the `Jenkinsfile` and added a `.travis.yml`

**Comment by tpunder** [comment]
Can you get it to fail on Linux?  Do we know why it doesn't fail consistently on Linux?  I want to make sure we understand the fix and don't create additional problems.

**Comment by er1c** [comment]
Yes, it also fails on linux too, I have a copy in the `ec2-user` home directory on the dev box.  It fails with random errors if you just rerun `sbt test`.  It does fail consistently on linux too now.  https://gist.github.com/er1c/e354f729f461ac8118ad67f717489353

**Comment by tpunder** [comment]
This isn't a valid fix.

Changing from `.abort` to `.close` causes potentially in-progress transactions to be committed depending on the state of the transaction.  However `ReusableTxn.close()` is only ever called from the `ReusableTxn.finalize()` method and the `LMDBEnvImpl.closeTransactions()` method.  Neither of which I would expect to cause any outstanding transaction to commit data.

This is a usage problem in the tests where the finalizers are being called mid-test which causes in-progress transactions to be closed.  The finalizers should either go away (especially since they are deprecated) or we need some sort of reference counting scheme when calling stuff like `.headMap`/`.tailMap` (which seems overly complicated).

Here is the correct fix:  https://github.com/eluvio/lmdb-je/commit/655c3abde70525fe427ac27c3555a35f23f54878

**Pull request closed without merging**
